%%% -*- coding: utf-8 -*-
%%% Copyright (C) 2014 Alex Kazinskiy
%%%
%%% This file is part of Combats Battle Manager
%%%
%%% Author contact: alboo@list.ru

%%% ====================================================================
%%% Описания приемов
%%% This file is autogenerated. Do not edit it.
%%% ====================================================================

-module(tricks).
-include_lib("bme.hrl").

%% ====================================================================
%% API functions
%% ====================================================================
-export([]).
-compile(export_all).

