%%% -*- coding: utf-8 -*-
%%% Copyright (C) 2014 Alex Kazinskiy
%%%
%%% This file is part of Combats Battle Manager
%%%
%%% Author contact: alboo@list.ru

%%% ====================================================================
%%% Описания приемов
%%% This file is autogenerated. Do not edit it.
%%% ====================================================================

-module(tricks).
-include_lib("bme.hrl").

%% ====================================================================
%% API functions
%% ====================================================================
-export([]).
-compile(export_all).

novice_hit() -> #trick{id = novice_hit, name = <<"Вломить"/utf8>>, decription = <<"Следующий удар наносит на 4 ед. больше урона"/utf8>>, class = novice, type = trick, tactics = #b_tactics{attack = 0, crit = 0, counter = 0, block = 0, parry = 0, hearts = 0, spirit = 0}, mana = 0, level = 0, stats = #u_stats{str = 0, agil = 0, int = 0, dex = 0, intel = 0, wisd = 0, spir = 0}, skills = #u_skills{knife = 0, axe = 0, hammer = 0, sword = 0, staff = 0, fire = 0, air = 0, water = 0, earth = 0, light = 0, dark = 0, gray = 0}, initial_delay = 0, delay = 4, class_delay = true, expend = false, require_target = false, target_type = any, self_buff = #u_buff{id = novice_hit, level = undefined, time = undefined}, enemy_buff = undefined, action = undefined}.
novice_def() -> #trick{id = novice_def, name = <<"Прикрыться"/utf8>>, decription = <<"Следующий удар по вам нанесет на 3 ед. меньше урона"/utf8>>, class = novice, type = trick, tactics = #b_tactics{attack = 0, crit = 0, counter = 0, block = 0, parry = 0, hearts = 0, spirit = 0}, mana = 0, level = 0, stats = #u_stats{str = 0, agil = 0, int = 0, dex = 0, intel = 0, wisd = 0, spir = 0}, skills = #u_skills{knife = 0, axe = 0, hammer = 0, sword = 0, staff = 0, fire = 0, air = 0, water = 0, earth = 0, light = 0, dark = 0, gray = 0}, initial_delay = 0, delay = 3, class_delay = true, expend = false, require_target = false, target_type = any, self_buff = #u_buff{id = novice_def, level = undefined, time = undefined}, enemy_buff = undefined, action = undefined}.
novice_hp() -> #trick{id = novice_hp, name = <<"Собрать Зубы"/utf8>>, decription = <<"Вы восстанавливаете от 2-5 HP"/utf8>>, class = novice, type = trick, tactics = #b_tactics{attack = 0, crit = 0, counter = 0, block = 0, parry = 0, hearts = 0, spirit = 1}, mana = 0, level = 0, stats = #u_stats{str = 0, agil = 0, int = 0, dex = 0, intel = 0, wisd = 0, spir = 0}, skills = #u_skills{knife = 0, axe = 0, hammer = 0, sword = 0, staff = 0, fire = 0, air = 0, water = 0, earth = 0, light = 0, dark = 0, gray = 0}, initial_delay = 0, delay = 4, class_delay = true, expend = false, require_target = false, target_type = any, self_buff = undefined, enemy_buff = undefined, action = fun(UnitPid) -> trick_helper:heal(novice_hp, UnitPid, #d_value{n = 1, k = 4}, false) end}.
hp_defence() -> #trick{id = hp_defence, name = <<"Стойкость"/utf8>>, decription = <<"Увеличивает вашу защиту от урона на 5% до конца боя. Можно применять трижды"/utf8>>, class = hp, type = trick, tactics = #b_tactics{attack = 0, crit = 0, counter = 0, block = 0, parry = 0, hearts = 5, spirit = 0}, mana = 0, level = 4, stats = #u_stats{str = 0, agil = 0, int = 0, dex = 0, intel = 0, wisd = 0, spir = 0}, skills = #u_skills{knife = 0, axe = 0, hammer = 0, sword = 0, staff = 0, fire = 0, air = 0, water = 0, earth = 0, light = 0, dark = 0, gray = 0}, initial_delay = 0, delay = 1, class_delay = true, expend = false, require_target = false, target_type = any, self_buff = #u_buff{id = hp_defence, level = undefined, time = undefined}, enemy_buff = undefined, action = undefined}.
hp_enrage() -> #trick{id = hp_enrage, name = <<"Ярость"/utf8>>, decription = <<"Увеличивает ваш урона на 5% до конца боя. Можно применять трижды."/utf8>>, class = hp, type = trick, tactics = #b_tactics{attack = 0, crit = 0, counter = 0, block = 0, parry = 0, hearts = 5, spirit = 0}, mana = 0, level = 4, stats = #u_stats{str = 0, agil = 0, int = 0, dex = 0, intel = 0, wisd = 0, spir = 0}, skills = #u_skills{knife = 0, axe = 0, hammer = 0, sword = 0, staff = 0, fire = 0, air = 0, water = 0, earth = 0, light = 0, dark = 0, gray = 0}, initial_delay = 0, delay = 1, class_delay = true, expend = false, require_target = false, target_type = any, self_buff = #u_buff{id = hp_enrage, level = undefined, time = undefined}, enemy_buff = undefined, action = undefined}.
